---
jupyter: python3
keep-ipynb: true
format:
  html:
    other-links:
      - text: Download Notebook
        icon: journal-code
        href: 2_ecosystem_overview.ipynb
title: "Terrestrial Ecosystems of {{< meta country-name >}}"
numbering:
  figure:
    enumerator: 2.%s
---

```{python}
#| echo: false
#| output: false
import os
from pprint import pprint

import geopandas as gpd
import yaml

import rle_python_gee
import iucn_get_data

print(f'{rle_python_gee.__version__ = }')
print(f'{iucn_get_data.__version__ = }')
```

```{python}
#| echo: false
#| output: false
# Load up the country-level configuration.
with open('../config/country_config.yaml', 'r') as f:
    config = yaml.safe_load(f)
pprint(config)
```

```{python}
#| echo: false
# Initialize Google Earth Engine.
rle_python_gee.ee_auth.initialize_ee(project=os.environ['GOOGLE_CLOUD_PROJECT'])
```


```{python}
#| echo: false
#| output: false
# Load the country's ecosystems data as a pandas DataFrame.
asset_id = config['ecosystem_gee_asset']['id']

ecosystems = rle_python_gee.Ecosystems(
    asset_id,
    get_level3_column='EFG1',
    get_level456_column='Glob_Typol'
)

ecosystems_df = ecosystems.functional_group_dataframe()
ecosystems_df
```

```{python}
#| echo: false
ecosystem_type_count = len(ecosystems_df)
biome_count = len(ecosystems_df.index.get_level_values('EFG1').unique())
```


The {{< meta country-name >}} ecosystem typology includes `{python} ecosystem_type_count` ecosystem types across `{python} biome_count` biomes (@tbl-typology).
The ecosystem typology is consistent with the IUCN global ecosystem typology [@keith2020get]
to support crosswalks and comparisons with Red Lists of ecosystems in other countries and
regions. The {{< meta country-name >}} ecosystem typology has a hierarchical structure, where each ecosystem type is assigned to a realm, biome and functional group (ecotype).
Realm refers to one of the four component media in the biosphere (Figure [2.1???]{.mark}),
biome is the segment of the biosphere united by major functional traits and macro-environmental features (Figure [2.2???]{.mark}),
and functional group is a group of related ecosystems within a biome (Figure [2.3???]{.mark}).
The distribution of {{< meta country-name >}}’s ecosystem types is shown in Figure [2.4]{.mark},
and map data is made publicly available ([reference?]{.mark}).

```{python}
#| echo: false
typology_es = iucn_get_data.Typology(
    language="spanish",
    ecosystems=ecosystems_df.drop(columns=['COD_new', 'ECRG', 'EFG2', 'EFG_Etter', 'GETyp_CODn'], errors='ignore'),
    ecosystems_functional_group_column='EFG1'
)
# typology_es.dataframe
```


```{python}
#| echo: false
#| label: tbl-typology
#| tbl-cap: "List of the terrestrial ecosystems of {{< meta country-name >}} developed in this project."
typology_es
```



::: {.content-hidden unless-meta="show-instructions"}

:::: {.callout-important}
## How to customize the Ecosystem Overview page

- To modify the ecosystem overview text, edit the `content/2_ecosystem_overview.qmd` file.
- To remove the ecosystem overview section, edit the `_quarto.yml` file and remove the
  `- content/2_ecosystem_overview.qmd` line.

**To hide these instructions on all pages, set `show-instructions: false`
in the `_quarto.yml` file.**
::::
:::
